import Head from 'next/head'
import Image from 'next/image'
import Login from './Login/login'


export default function Home() {
    return ( 
        <div>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <meta charset="UTF-8"/>
                <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
                <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
                <title>Login Page</title>
            </Head>
            <Login>
            </Login>
        </div>

    );
}